# Generated by Django 3.1.1 on 2020-12-27 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmd.restaurant')),
            ],
        ),
    ]
