# Generated by Django 3.1.1 on 2020-12-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd', '0002_restaurantreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininghallreview',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
