# Generated by Django 3.1.1 on 2020-12-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd', '0003_auto_20201227_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininghallreview',
            name='comment',
            field=models.CharField(default='default', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='comment',
            field=models.CharField(default='default', max_length=2000),
            preserve_default=False,
        ),
    ]
