# Generated by Django 3.1.1 on 2020-12-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd', '0004_auto_20201227_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininghallreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
