# Generated by Django 3.1.1 on 2020-12-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd', '0005_auto_20201228_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininghall',
            name='urlName',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='urlName',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='urlName',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
