# Generated by Django 3.1.4 on 2021-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd', '0006_auto_20201228_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininghallreview',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='rating',
            field=models.FloatField(),
        ),
    ]
